# Bellabeat Case Study — FitBit Data Analysis
## Google Data Analytics Capstone Project
### By Aniqa Raihana

## Business Task
Analysis FitBit fitness tracker data to identify trends in smart device usage and apply insights to Bellabeat marketing strategy 


## Stakeholders
- Urška Sršen (Cofounder)
- Sando Mur (Cofounder)
- Bellabeat Marketing Team

In [17]:
print("Needed Libraries Loaded")

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

Needed Libraries Loaded

In [18]:
print("Loaded all the needed datasets")

# Folder 1 (March - April)
daily_activity_1 = pd.read_csv('/kaggle/input/datasets/aniqaraihana/bellabeat-casestudy-fitbit-data1/dailyActivity_merged.csv')
hourly_steps_1 = pd.read_csv('/kaggle/input/datasets/aniqaraihana/bellabeat-casestudy-fitbit-data1/hourlySteps_merged.csv')
weigth_log_info_1 = pd.read_csv('/kaggle/input/datasets/aniqaraihana/bellabeat-casestudy-fitbit-data1/weightLogInfo_merged.csv')

# Folder 2 (April - May)
daily_activity_2 = pd.read_csv('/kaggle/input/datasets/aniqaraihana/bellabeat-casestudy-fitbit-data1/dailyActivity_merged (2).csv')
hourly_steps_2 = pd.read_csv('/kaggle/input/datasets/aniqaraihana/bellabeat-casestudy-fitbit-data1/hourlySteps_merged (2).csv')
weigth_log_info_2 = pd.read_csv('/kaggle/input/datasets/aniqaraihana/bellabeat-casestudy-fitbit-data1/weightLogInfo_merged (2).csv')
#sleep_Day 
sleep_Day = pd.read_csv('/kaggle/input/datasets/aniqaraihana/bellabeat-casestudy-fitbit-data1/sleepDay_merged(2).csv')

Loaded all the needed datasets

In [19]:
# merging TWO folders ( March - April and April - May) - March to May
daily_activity = pd.concat([daily_activity_1 , daily_activity_2 ], ignore_index=True)
hourly_steps = pd.concat([hourly_steps_1 , hourly_steps_2] , ignore_index=True)
weight_log_info = pd.concat([weigth_log_info_1 , weigth_log_info_2] , ignore_index=True)

In [20]:
daily_activity[daily_activity.duplicated()]

Empty DataFrame
Columns: [Id, ActivityDate, TotalSteps, TotalDistance, TrackerDistance, LoggedActivitiesDistance, VeryActiveDistance, ModeratelyActiveDistance, LightActiveDistance, SedentaryActiveDistance, VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes, SedentaryMinutes, Calories]
Index: []

### Cleaning Note
Duplicate rows were found in hourly_steps (175 rows) 
and weight_log_info (2 rows). These duplicates occur 
on April 12, 2016 — the overlap date between Folder 1 
and Folder 2. Duplicates will be removed.

### Duplicate Check Results

| Table | Duplicates Found | Reason |
|-------|-----------------|--------|
| daily_activity | 0 | No duplicates ✅ |
| hourly_steps | 175 | April 12 overlap between folders ⚠️ |
| weight_log_info | 2 | April 12 overlap between folders ⚠️ |
| sleep | 3 | Device sync errors ⚠️ |

### Action Taken
Duplicates removed from hourly_steps, weight_log_info, 
and sleep using drop_duplicates().
daily_activity required no action.

In [21]:

hourly_steps[hourly_steps.duplicated()]

               Id           ActivityHour  StepTotal
24801  1624580081  4/12/2016 12:00:00 AM         31
24802  1624580081   4/12/2016 1:00:00 AM          0
24803  1624580081   4/12/2016 2:00:00 AM          0
24804  1624580081   4/12/2016 3:00:00 AM          7
24805  1624580081   4/12/2016 4:00:00 AM          0
...           ...                    ...        ...
45452  8877689391   4/12/2016 4:00:00 AM          0
45453  8877689391   4/12/2016 5:00:00 AM          0
45454  8877689391   4/12/2016 6:00:00 AM        209
45455  8877689391   4/12/2016 7:00:00 AM        964
45456  8877689391   4/12/2016 8:00:00 AM        834

[175 rows x 3 columns]

In [22]:
weight_log_info[weight_log_info.duplicated()]

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
46,6962181067,4/12/2016 11:59:59 PM,62.500000,137.788914,NaN,24.389999,True,1460505599000
76,8877689391,4/12/2016 6:47:11 AM,85.800003,189.156628,NaN,25.680000,False,1460443631000

In [23]:

sleep_Day[sleep_Day.duplicated()]

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
161,4388161847,5/5/2016 12:00:00 AM,1,471,495
223,4702921684,5/7/2016 12:00:00 AM,1,520,543
380,8378563200,4/25/2016 12:00:00 AM,1,388,402

## Removing Duplicates

In [24]:
daily_activity = daily_activity.drop_duplicates()
hourly_steps = hourly_steps.drop_duplicates()
weight_log_info = weight_log_info.drop_duplicates()
sleep_Day = sleep_Day.drop_duplicates()

In [25]:
print("=== AFTER REMOVING DUPLICATES ===")
print(f'daily_activity data : {len(daily_activity)}')
print(f'hourly_steps data : {len(hourly_steps)}')
print(f'weight_log_info data : {len(weight_log_info)}')
print(f'sleep_Day data : {len(sleep_Day)}')

=== AFTER REMOVING DUPLICATES ===
daily_activity data : 1397
hourly_steps data : 46008
weight_log_info data : 98
sleep_Day data : 410

## Date formats fixed!

In [26]:
daily_activity['ActivityDate'] = pd.to_datetime(daily_activity['ActivityDate'])

In [42]:
hourly_steps['ActivityHour'] = pd.to_datetime(hourly_steps['ActivityHour'])

In [43]:
weight_log_info['Date'] = pd.to_datetime(weight_log_info['Date'])

In [44]:
sleep_Day['SleepDay'] = pd.to_datetime(sleep_Day['SleepDay'])

### Removing unnecessary columns

In [30]:
# Drop unnecessary columns from daily_activity
columns_to_drop = [
    'TotalDistance',
    'TrackerDistance', 
    'LoggedActivitiesDistance',
    'VeryActiveDistance',
    'ModeratelyActiveDistance',
    'LightActiveDistance',
    'SedentaryActiveDistance'
]

daily_activity = daily_activity.drop(columns=columns_to_drop)

In [31]:
# Drop unnecessary columns from weight_log_info
weight_log_info = weight_log_info.drop(columns=[
    'Fat',
    'WeightPounds', 
    'IsManualReport',
    'LogId'
])

In [32]:
# Also drop from sleep
sleep_Day = sleep_Day.drop(columns=['TotalSleepRecords'])

In [48]:
daily_activity.to_csv('daily_activity_clean.csv', index=False)

In [49]:
hourly_steps.to_csv('hourly_steps_clean.csv', index=False)

In [50]:
sleep_Day.to_csv('sleep_day_clean.csv', index=False)

In [51]:
weight_log_info.to_csv('weight_log_info_clean.csv', index=False)

In [38]:
# daily_activity.head(20)

In [39]:
# hourly_steps.head(20)

In [40]:
# weight_log_info.head(20)

In [41]:

# sleep_Day.head(20)